import {
  BarChart,
  BookOpen,
  Dumbbell,
  GraduationCap,
  MessageSquare,
  Trophy,
  Users,
  Video,
} from 'lucide-react';
import Link from 'next/link';
import { metadata } from '../metadata';

export const generateMetadata = () => {
  return {
    ...metadata,
    title: 'Help Center | HalteresAI',
    description:
      'Find answers about HalteresAI for coaches and athletes. Programming, leaderboards, AI feedback, and more.',
  };
};

export default function HelpPage() {
  const coachFaqs = [
    {
      question: 'How do I set up my gym profile and equipment?',
      answer:
        "You can configure your gym's equipment inventory in the Program Writer. This ensures all generated programming uses only the equipment you actually have—no more workouts assuming sleds or machines you don't own.",
    },
    {
      question: 'Can I edit the workouts generated by HalteresAI?',
      answer:
        "Yes! You can customize every aspect of any workout. Use the Enhance feature to modify workouts instantly when equipment breaks or class size changes—something generic programming services can't do.",
    },
    {
      question: 'How far in advance can I program workouts?',
      answer:
        'You can generate up to 8 weeks of programming at once. The calendar view makes it easy to see and manage your entire programming schedule.',
    },
    {
      question: 'How do I invite athletes to my gym?',
      answer:
        'Go to your Gym Settings in the dashboard to find your unique invite code. Share this code with your members—they can use it to join your gym on the mobile app and instantly access workouts, leaderboards, and AI feedback.',
    },
    {
      question: 'How does the AI feedback system work?',
      answer:
        "The AI learns from two sources: your ratings and feedback on generated workouts, and athlete feedback after logging results. Over time, programming becomes more tailored to your gym's preferences.",
    },
    {
      question: 'What if I need help with a specific feature?',
      answer: 'Our team is available to help! You can reach us by emailing ben@halteres.ai.',
    },
  ];

  const athleteFaqs = [
    {
      question: 'How do I join my gym on HalteresAI?',
      answer:
        "Download the HalteresAI app and enter the invite code provided by your coach. You'll be connected to your gym and can immediately see today's workout.",
    },
    {
      question: 'How do I log my workout results?',
      answer:
        'After completing a workout, tap on it in the app and enter your results (time, reps, or weight). You can mark whether you went RX or scaled, and add notes about how it felt.',
    },
    {
      question: 'How do leaderboards work?',
      answer:
        'You earn points for participating: completing workouts (+3), hitting PRs (+2), going RX (+1), and placing 1st/2nd/3rd (+10/+7/+5). Points accumulate on weekly and monthly leaderboards.',
    },
    {
      question: 'What is AI feedback?',
      answer:
        'After logging a workout, you can request AI feedback. The AI analyzes your performance, compares it to your history, and provides personalized tips and observations.',
    },
    {
      question: 'How do I update my profile and metrics?',
      answer:
        'Go to the Profile tab in the app. You can update your display name, 1RM lifts, mile time, and body metrics anytime. Keeping these updated helps the AI provide better feedback.',
    },
    {
      question: 'Can I see my progress over time?',
      answer:
        'Yes! The app tracks your workout history, PRs, and shows weekly AI-generated trends analyzing your improvement and areas to focus on.',
    },
  ];

  return (
    <div className="min-h-screen bg-white">
      <main>
        {/* Hero section */}
        <div className="bg-blue-600 py-24 sm:py-32">
          <div className="mx-auto max-w-7xl px-6 lg:px-8">
            <div className="mx-auto max-w-2xl text-center">
              <h1 className="text-4xl font-bold tracking-tight text-white sm:text-6xl">
                Help Center
              </h1>
              <p className="mt-6 text-lg leading-8 text-blue-100">
                Resources for coaches and athletes. Learn how to generate programming, use
                leaderboards, get AI feedback, and more.
              </p>
            </div>
          </div>
        </div>

        {/* Resources grid */}
        <div className="py-24 sm:py-32">
          <div className="mx-auto max-w-7xl px-6 lg:px-8">
            <div className="mx-auto max-w-2xl text-center">
              <h2 className="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">
                Resources
              </h2>
              <p className="mt-6 text-lg leading-8 text-gray-600">
                Guides and tutorials for both coaches and athletes.
              </p>
            </div>
            <div className="mx-auto mt-16 max-w-2xl sm:mt-20 lg:max-w-4xl">
              <div className="grid grid-cols-1 gap-x-8 gap-y-10 lg:grid-cols-2 lg:gap-y-16">
                <div className="relative pl-16">
                  <div className="absolute left-0 top-0 flex h-10 w-10 items-center justify-center rounded-lg bg-blue-600">
                    <BookOpen className="h-6 w-6 text-white" aria-hidden="true" />
                  </div>
                  <h3 className="text-base font-semibold leading-7 text-gray-900">
                    Coach Getting Started
                  </h3>
                  <p className="mt-2 text-base leading-7 text-gray-600">
                    Set up your gym, configure equipment, and generate your first 8-week programming
                    cycle.
                  </p>
                  <Link
                    href="/tutorials"
                    className="text-sm font-semibold leading-6 text-blue-600 hover:text-blue-500"
                  >
                    Read the guide <span aria-hidden="true">→</span>
                  </Link>
                </div>
                <div className="relative pl-16">
                  <div className="absolute left-0 top-0 flex h-10 w-10 items-center justify-center rounded-lg bg-green-600">
                    <Dumbbell className="h-6 w-6 text-white" aria-hidden="true" />
                  </div>
                  <h3 className="text-base font-semibold leading-7 text-gray-900">
                    Athlete App Guide
                  </h3>
                  <p className="mt-2 text-base leading-7 text-gray-600">
                    Learn how to join your gym, log workouts, compete on leaderboards, and get AI
                    feedback.
                  </p>
                  <Link
                    href="/tutorials"
                    className="text-sm font-semibold leading-6 text-blue-600 hover:text-blue-500"
                  >
                    View athlete guide <span aria-hidden="true">→</span>
                  </Link>
                </div>
                <div className="relative pl-16">
                  <div className="absolute left-0 top-0 flex h-10 w-10 items-center justify-center rounded-lg bg-yellow-500">
                    <Trophy className="h-6 w-6 text-white" aria-hidden="true" />
                  </div>
                  <h3 className="text-base font-semibold leading-7 text-gray-900">
                    Leaderboards & Points
                  </h3>
                  <p className="mt-2 text-base leading-7 text-gray-600">
                    Understand how the points system works and how to use leaderboards to motivate
                    your athletes.
                  </p>
                  <Link
                    href="/tutorials"
                    className="text-sm font-semibold leading-6 text-blue-600 hover:text-blue-500"
                  >
                    Learn about leaderboards <span aria-hidden="true">→</span>
                  </Link>
                </div>
                <div className="relative pl-16">
                  <div className="absolute left-0 top-0 flex h-10 w-10 items-center justify-center rounded-lg bg-purple-600">
                    <MessageSquare className="h-6 w-6 text-white" aria-hidden="true" />
                  </div>
                  <h3 className="text-base font-semibold leading-7 text-gray-900">
                    AI Feedback System
                  </h3>
                  <p className="mt-2 text-base leading-7 text-gray-600">
                    Discover how the AI learns from coaches and athletes to provide better
                    programming and insights.
                  </p>
                  <Link
                    href="/tutorials"
                    className="text-sm font-semibold leading-6 text-blue-600 hover:text-blue-500"
                  >
                    Explore AI features <span aria-hidden="true">→</span>
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* FAQ section */}
        <div className="bg-gray-50 py-24 sm:py-32">
          <div className="mx-auto max-w-7xl px-6 lg:px-8">
            <div className="mx-auto max-w-4xl">
              <h2 className="text-2xl font-bold leading-10 tracking-tight text-gray-900">
                Frequently Asked Questions
              </h2>

              {/* Coach FAQs */}
              <div className="mt-10">
                <h3 className="text-xl font-semibold text-blue-600 mb-6 flex items-center">
                  <Users className="h-5 w-5 mr-2" />
                  For Coaches & Gym Owners
                </h3>
                <dl className="space-y-8">
                  {coachFaqs.map((faq, index) => (
                    <div key={index} className="border-b border-gray-200 pb-8">
                      <dt className="text-lg font-semibold leading-7 text-gray-900">
                        {faq.question}
                      </dt>
                      <dd className="mt-4 text-base leading-7 text-gray-600">{faq.answer}</dd>
                    </div>
                  ))}
                </dl>
              </div>

              {/* Athlete FAQs */}
              <div className="mt-16">
                <h3 className="text-xl font-semibold text-green-600 mb-6 flex items-center">
                  <Dumbbell className="h-5 w-5 mr-2" />
                  For Athletes
                </h3>
                <dl className="space-y-8">
                  {athleteFaqs.map((faq, index) => (
                    <div key={index} className="border-b border-gray-200 pb-8">
                      <dt className="text-lg font-semibold leading-7 text-gray-900">
                        {faq.question}
                      </dt>
                      <dd className="mt-4 text-base leading-7 text-gray-600">{faq.answer}</dd>
                    </div>
                  ))}
                </dl>
              </div>
            </div>
          </div>
        </div>

        {/* Contact us section */}
        <div className="py-24 sm:py-32">
          <div className="mx-auto max-w-7xl px-6 lg:px-8">
            <div className="mx-auto max-w-2xl text-center">
              <h2 className="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">
                Still need help?
              </h2>
              <p className="mt-6 text-lg leading-8 text-gray-600">
                Our support team is ready to assist you with any questions or issues you might have.
              </p>
              <div className="mt-10 flex items-center justify-center gap-x-6">
                <Link
                  href="/contact"
                  className="rounded-md bg-blue-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-blue-500"
                >
                  Contact Support
                </Link>
                <Link href="/support" className="text-sm font-semibold leading-6 text-blue-600">
                  View support options <span aria-hidden="true">→</span>
                </Link>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
