import { metadata } from '../metadata';
import Link from 'next/link';
import { BookOpen, Video, BarChart, GraduationCap } from 'lucide-react';

export const generateMetadata = () => {
  return {
    ...metadata,
    title: 'Help Center | HalteresAI',
    description:
      'Find answers to common questions, tutorials, and resources to help you get the most out of HalteresAI.',
  };
};

export default function HelpPage() {
  const faqs = [
    {
      question: 'How do I set up my gym profile?',
      answer:
        'You can select your gym from the dropdown menu in the top right corner of the Program Writer. This will pre-select your equipment and gym details for you.',
    },
    {
      question: 'Can I edit the workouts generated by HalteresAI?',
      answer:
        'Yes! After generating a workout, you can customize every aspect of it. You can modify exercises, adjust timing, change rep schemes, and more. The intuitive editor makes it easy to fine-tune any workout to meet your specific needs.',
    },
    {
      question: 'How far in advance can I program workouts?',
      answer:
        'You can program workouts as far in advance as you need. HalteresAI allows you to create programming for days, weeks, or even months ahead. The calendar view makes it easy to see and manage your programming schedule.',
    },
    {
      question: 'Can I share workouts with my clients or staff?',
      answer:
        'Yes, you can share workouts in several ways. Copy them as text to paste into emails or your own system. PDF export and social media sharing coming soon!',
    },
    {
      question: 'What if I need help with a specific feature?',
      answer:
        'Our team is available to help! You can reach us through the chat feature in the app, by emailing ben@halteres.ai.',
    },
  ];

  return (
    <div className="min-h-screen bg-white">
      <main>
        {/* Hero section */}
        <div className="bg-blue-600 py-24 sm:py-32">
          <div className="mx-auto max-w-7xl px-6 lg:px-8">
            <div className="mx-auto max-w-2xl text-center">
              <h1 className="text-4xl font-bold tracking-tight text-white sm:text-6xl">
                Help Center
              </h1>
              <p className="mt-6 text-lg leading-8 text-blue-100">
                Find answers, tutorials, and resources to help you get the most
                out of HalteresAI.
              </p>
            </div>
          </div>
        </div>

        {/* Resources grid */}
        <div className="py-24 sm:py-32">
          <div className="mx-auto max-w-7xl px-6 lg:px-8">
            <div className="mx-auto max-w-2xl text-center">
              <h2 className="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">
                Resources
              </h2>
              <p className="mt-6 text-lg leading-8 text-gray-600">
                Explore our guides, tutorials, and documentation to help you
                master HalteresAI.
              </p>
            </div>
            <div className="mx-auto mt-16 max-w-2xl sm:mt-20 lg:max-w-4xl">
              <div className="grid grid-cols-1 gap-x-8 gap-y-10 lg:grid-cols-2 lg:gap-y-16">
                <div className="relative pl-16">
                  <div className="absolute left-0 top-0 flex h-10 w-10 items-center justify-center rounded-lg bg-blue-600">
                    <BookOpen
                      className="h-6 w-6 text-white"
                      aria-hidden="true"
                    />
                  </div>
                  <h3 className="text-base font-semibold leading-7 text-gray-900">
                    Getting Started Guide
                  </h3>
                  <p className="mt-2 text-base leading-7 text-gray-600">
                    Learn how to set up your account, configure your gym, and
                    create your first workout in minutes.
                  </p>
                  <Link
                    href="#"
                    className="text-sm font-semibold leading-6 text-blue-600 hover:text-blue-500"
                  >
                    Read the guide <span aria-hidden="true">→</span>
                  </Link>
                </div>
                <div className="relative pl-16">
                  <div className="absolute left-0 top-0 flex h-10 w-10 items-center justify-center rounded-lg bg-blue-600">
                    <Video className="h-6 w-6 text-white" aria-hidden="true" />
                  </div>
                  <h3 className="text-base font-semibold leading-7 text-gray-900">
                    Video Tutorials
                  </h3>
                  <p className="mt-2 text-base leading-7 text-gray-600">
                    Watch step-by-step videos on how to use all features of the
                    HalteresAI platform.
                  </p>
                  <Link
                    href="#"
                    className="text-sm font-semibold leading-6 text-blue-600 hover:text-blue-500"
                  >
                    Watch tutorials <span aria-hidden="true">→</span>
                  </Link>
                </div>
                <div className="relative pl-16">
                  <div className="absolute left-0 top-0 flex h-10 w-10 items-center justify-center rounded-lg bg-blue-600">
                    <BarChart
                      className="h-6 w-6 text-white"
                      aria-hidden="true"
                    />
                  </div>
                  <h3 className="text-base font-semibold leading-7 text-gray-900">
                    Programming Best Practices
                  </h3>
                  <p className="mt-2 text-base leading-7 text-gray-600">
                    Learn how to create effective programming cycles and
                    periodization plans for different client goals.
                  </p>
                  <Link
                    href="#"
                    className="text-sm font-semibold leading-6 text-blue-600 hover:text-blue-500"
                  >
                    View best practices <span aria-hidden="true">→</span>
                  </Link>
                </div>
                <div className="relative pl-16">
                  <div className="absolute left-0 top-0 flex h-10 w-10 items-center justify-center rounded-lg bg-blue-600">
                    <GraduationCap
                      className="h-6 w-6 text-white"
                      aria-hidden="true"
                    />
                  </div>
                  <h3 className="text-base font-semibold leading-7 text-gray-900">
                    Advanced Features
                  </h3>
                  <p className="mt-2 text-base leading-7 text-gray-600">
                    Discover advanced techniques for customizing workouts and
                    maximizing the platform's capabilities.
                  </p>
                  <Link
                    href="#"
                    className="text-sm font-semibold leading-6 text-blue-600 hover:text-blue-500"
                  >
                    Explore advanced features <span aria-hidden="true">→</span>
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* FAQ section */}
        <div className="bg-gray-50 py-24 sm:py-32">
          <div className="mx-auto max-w-7xl px-6 lg:px-8">
            <div className="mx-auto max-w-4xl">
              <h2 className="text-2xl font-bold leading-10 tracking-tight text-gray-900">
                Frequently asked questions
              </h2>
              <p className="mt-6 text-base leading-7 text-gray-600">
                Find answers to common questions about using HalteresAI.
              </p>
              <div className="mt-10">
                <dl className="space-y-8">
                  {faqs.map((faq, index) => (
                    <div key={index} className="border-b border-gray-200 pb-8">
                      <dt className="text-lg font-semibold leading-7 text-gray-900">
                        {faq.question}
                      </dt>
                      <dd className="mt-4 text-base leading-7 text-gray-600">
                        {faq.answer}
                      </dd>
                    </div>
                  ))}
                </dl>
              </div>
            </div>
          </div>
        </div>

        {/* Contact us section */}
        <div className="py-24 sm:py-32">
          <div className="mx-auto max-w-7xl px-6 lg:px-8">
            <div className="mx-auto max-w-2xl text-center">
              <h2 className="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">
                Still need help?
              </h2>
              <p className="mt-6 text-lg leading-8 text-gray-600">
                Our support team is ready to assist you with any questions or
                issues you might have.
              </p>
              <div className="mt-10 flex items-center justify-center gap-x-6">
                <Link
                  href="/contact"
                  className="rounded-md bg-blue-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-blue-500"
                >
                  Contact Support
                </Link>
                <Link
                  href="/support"
                  className="text-sm font-semibold leading-6 text-blue-600"
                >
                  View support options <span aria-hidden="true">→</span>
                </Link>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
