const equipmentList = [
  { value: 1, label: 'Barbell' },
  { value: 2, label: 'Bumper Plates' },
  { value: 3, label: 'Power Rack' },
  { value: 4, label: 'Kettlebell' },
  { value: 46, label: 'Rower' },
  { value: 47, label: 'Treadmill' },
  { value: 5, label: 'Dumbbell' },
  { value: 10, label: 'Air Bike' },
  { value: 6, label: 'Jump Rope' },
  { value: 7, label: 'Medicine Ball' },
  { value: 8, label: 'Plyo Box' },
  { value: 11, label: 'SkiErg' },
  { value: 12, label: 'Wall Ball' },
  { value: 14, label: 'Gymnastic Rings' },
  { value: 15, label: 'Climbing Rope' },
  { value: 16, label: 'Resistance Bands' },
  { value: 17, label: 'Sled' },
  { value: 18, label: 'Battle Ropes' },
  { value: 19, label: 'AbMat' },
  { value: 20, label: 'Weight Vest' },
  { value: 21, label: 'Hex Bar' },
  { value: 22, label: 'Slam Ball' },
  { value: 23, label: 'Sandbags' },
  { value: 24, label: 'Foam Roller' },
  { value: 25, label: 'Lacrosse Ball' },
  { value: 26, label: 'PVC Pipe' },
  { value: 27, label: 'Yoga Mat' },
  { value: 35, label: 'Suspension Trainer' },
  { value: 36, label: 'Safety Squat Bar' },
  { value: 37, label: 'Swiss Bar' },
  { value: 38, label: 'Parallettes' },
  { value: 39, label: 'Smith Machine' },
  { value: 40, label: 'Leg Press Machine' },
  { value: 41, label: 'Dip Machine' },
  { value: 42, label: 'GHD Machine' },
  { value: 44, label: 'Stationary Bike' },
  { value: 45, label: 'Elliptical' },
  { value: 49, label: 'Climbing Wall' },
  // Triathlon-specific equipment
  { value: 50, label: 'Swimming Pool' },
  { value: 51, label: 'Open Water Access' },
  { value: 52, label: 'Road Bike' },
  { value: 53, label: 'Time Trial/Tri Bike' },
  { value: 54, label: 'Bike Trainer/Turbo' },
  { value: 55, label: 'Power Meter' },
  { value: 56, label: 'Heart Rate Monitor' },
  { value: 57, label: 'Wetsuit' },
  { value: 58, label: 'Running Track' },
  { value: 59, label: 'Trail Access' },
  { value: 60, label: 'Bike Computer/GPS' },
  { value: 61, label: 'Nutrition/Hydration System' },
  { value: 62, label: 'Recovery Tools (Ice Bath/Compression)' },
];

export default equipmentList;
