const equipmentList = [
  { value: 1, label: 'Barbell' },
  { value: 2, label: 'Dumbbell' },
  { value: 3, label: 'Kettlebell' },
  { value: 4, label: 'Pull-up Bar' },
  { value: 5, label: 'Jump Rope' },
  { value: 6, label: 'Medicine Ball' },
  { value: 7, label: 'Box for Box Jumps' },
  { value: 8, label: 'Rowing Machine' },
  { value: 9, label: 'Treadmill' },
  { value: 10, label: 'Stationary Bike' },
  { value: 11, label: 'Elliptical' },
  { value: 12, label: 'Weight Plates' },
  { value: 13, label: 'Bench Press' },
  { value: 14, label: 'Squat Rack' },
  { value: 15, label: 'Leg Press Machine' },
  { value: 17, label: 'Smith Machine' },
  { value: 24, label: 'Dip Machine' },
  { value: 25, label: 'GHD' },
  { value: 26, label: 'Plyo Box' },
  { value: 27, label: 'Wall Ball' },
  { value: 28, label: 'AbMat' },
  { value: 29, label: 'Battle Ropes' },
  { value: 30, label: 'Climbing Rope' },
  { value: 31, label: 'Prowler Sled' },
  { value: 32, label: 'Gymnastic Rings' },
  { value: 33, label: 'Parallettes' },
  { value: 34, label: 'Weight Vest' },
  { value: 35, label: 'Hex Bar' },
  { value: 36, label: 'Resistance Bands' },
  { value: 37, label: 'Sandbag' },
  { value: 38, label: 'Slam Ball' },
  { value: 39, label: 'Speed Rope' },
  { value: 40, label: 'Suspension Trainer' },
  { value: 41, label: 'Weightlifting Belt' },
  { value: 42, label: 'Wrist Wraps' },
  { value: 43, label: 'Chalk' },
  { value: 44, label: 'Foam Roller' },
  { value: 45, label: 'Lacrosse Ball' },
  { value: 46, label: 'PVC Pipe' },
  { value: 47, label: 'Yoga Mat' },
  { value: 48, label: 'Yoga Block' },
  { value: 49, label: 'Knee Sleeves' },
  { value: 50, label: 'Lifting Straps' },
];

export default equipmentList;
